#!/usr/bin/env python3
import socket, os, json
sock_path = os.environ.get("NESTOR_SOCKET")
s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
s.connect(sock_path)
req1 = json.dumps({"action": "get", "path": "variables.test_var"}) + "\n"
s.sendall(req1.encode())
resp1 = s.recv(1024).decode()
data1 = json.loads(resp1.strip())
s2 = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
s2.connect(sock_path)
req2 = json.dumps({"action": "set", "path": "variables.plugin_updated", "value": "yes_it_works"}) + "\n"
s2.sendall(req2.encode())
resp2 = s2.recv(1024).decode()
print(json.dumps({"received_val": data1["value"]}))
