#ifndef _NESTOR_ERROR_CODES_H
#define _NESTOR_ERROR_CODES_H

#define ERR_SUCCESS 0
#define ERR_OOM -1
#define ERR_CYCLIC_DEP -2
#define ERR_MISSING_VAR -3
#define ERR_CLI_UNSUPPORTED_BLOCKING_NODE -4
#define ERR_LOOP_MAX_ITERATIONS -5
#define ERR_HTTP_TRANSPORT -6
#define ERR_INVALID_BOUNDARY -7
#define ERR_LOCKED -8

#endif
